#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("hellotest.Resource", IsApplication=true)]

namespace hellotest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int action_settings = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int btnCancel = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int myButton = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int webView1 = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int authentication = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int login = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int token = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int app_loading = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int broker_authentication_request_is_invalid = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int broker_processing = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int button_cancel = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int confirmation_activity_authentication = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int default_not_supported_msg = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int error_token_type_not_supported = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int hello = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int hello_world = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int title_activity_authentication = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int title_activity_login = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int title_activity_token = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int title_confirmation_activity_authentication = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Mono_Android_Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
